version: '3'
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=cisco_mdt
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=telegraf
      - INFLUXDB_USER=murafi
      - INFLUXDB_USER_PASSWORD=telegraf
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb_data:/var/lib/influxdb"
      # - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    networks:
      - tig_network
    restart: unless-stopped

  telegraf:
    image: telegraf:1.19.0
    container_name: telegraf
    ports:
      - "57000:57000"
    # user: "1000"
    volumes:
      - "./telegraf_data/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - tig_network 
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: always

  grafana:
    image: grafana/grafana:8.1.0-ubuntu
    container_name: grafana
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_data:/var/lib/grafana"
    networks:
      - tig_network 
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: always

networks:
  tig_network:
